name: Security Quick Scan

on:
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:

  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2

  dependency-review:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/dependency-review-action@v4

  semgrep:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: returntocorp/semgrep-action@v1
        with:
          config: p/owasp-top-ten