name: OWASP ZAP DAST

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Target URL"
        required: true
        type: string

jobs:
  zap:
    runs-on: ubuntu-latest

    steps:
      - name: OWASP ZAP Baseline
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: ${{ inputs.target }}